name: deploy page
run-name: ${{ github.actor }} deploy
on: 
  push:
    branches:
      - "main"
      - "master"

jobs:
  deploy-gh-pages:
      runs-on : ubuntu-latest
      steps:
        - uses : actions/checkout@v3
          with:
            token : ${{ github.token }}
        - uses : actions/setup-node@v3
          with : 
            node-version : 16
            cache : 'yarn'
        # - run : git remote rm origin
        - run : |
            git config --global user.email "${{ github.event.pusher.email }}"
            git config --global user.name "${{ github.actor }}"
        - run : npm install -g yarn
        - run : yarn
        - run : PUBLIC_URL=/${{ github.event.repository.name }} yarn build
        - name : deploy
          run: |
            cd ./build
            git init -b gh-pages
            git remote add -t gh-pages origin \
            https://git:${{ github.token }}@github.com/${{ github.repository }}.git
            git fetch -u origin gh-pages:gh-pages
            git add .
            git commit -m "${{ github.actor }} deploy"
            git push origin gh-pages -f
            cd ..   